name: yunderaterminalpass

services:
  yunderaterminalpass:
    image: krizcold/nginxhashlock:latest
    container_name: yunderaterminalpass
    restart: unless-stopped
    expose:
      - "3000"
    user: "root"
    environment:
      USER: $USER
      PASSWORD: $PASSWORD
      SESSION_DURATION_HOURS: "720"  # 30 days (default)
      BACKEND_HOST: "ttydpass"
      BACKEND_PORT: "7681"
      LISTEN_PORT: "3000"
      # ALLOWED_EXTENSIONS: "js,css,png,ico,svg"
      # ↑ Uncomment to allow static assets without auth
      # ↑ Not needed for terminal - ttyd serves self-contained HTML
      # ALLOWED_PATHS: "api/health"
      # ↑ Uncomment to allow public pages/APIs without auth
      # ↑ Example: /api/health accessible without login
    depends_on:
      - ttydpass
    networks:
      - pcs
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN

  ttydpass:
    image: tsl0922/ttyd:latest
    container_name: yunderaterminalpassttyd
    restart: unless-stopped
    user: "root"
    command: ["ttyd", "--writable", "--client-option", "enableZmodem=true", "--client-option", "enableSixel=false", "--client-option", "enableTrzsz=false", "--terminal-type", "xterm-256color", "chroot", "/host", "bash"]
    volumes:
      - type: bind
        source: /
        target: /host
    networks:
      - pcs
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN

networks:
  pcs:
    external: true

x-casaos:
  architectures:
    - amd64
    - arm64
  main: yunderaterminalpass
  author: yundera
  developer: yundera
  icon: https://cdn-icons-png.flaticon.com/512/2933/2933245.png
  tagline:
    en_us: "Secure password-protected terminal access"
  category: Utilities
  description:
    en_us: "A secure terminal with username/password authentication using nginxhashlock. Login with credentials for session-based access with configurable duration."
  title:
    en_us: "Yundera Terminal (Password Auth)"
  store_app_id: yunderaterminalpass
  is_uncontrolled: false
  # nginxhashlock will show login page - no hash needed
  index: /
  webui_port: 3000
