name: yunderaterminalboth

services:
  yunderaterminalboth:
    image: ghcr.io/yundera/nginx-hash-lock:latest
    container_name: yunderaterminalboth
    restart: unless-stopped
    expose:
      - 80
    user: "root"
    environment:
      # Both authentication methods enabled - accept either!
      AUTH_HASH: $AUTH_HASH
      USER: $USER
      PASSWORD: $PASSWORD
      SESSION_DURATION_HOURS: "168"  # 1 week
      BACKEND_HOST: "ttydboth"
      BACKEND_PORT: "7681"
      LISTEN_PORT: "80"
      # ALLOWED_EXTENSIONS: "js,css,png,ico,svg"
      # ↑ Uncomment to allow static assets without auth
      # ALLOWED_PATHS: "api/health"
      # ↑ Uncomment to allow public pages/APIs without auth
    depends_on:
      - ttydboth
    networks:
      - pcs
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN

  ttydboth:
    image: tsl0922/ttyd:latest
    container_name: yunderaterminalbothttyd
    restart: unless-stopped
    user: "root"
    command: ["ttyd", "--writable", "--client-option", "enableZmodem=true", "--client-option", "enableSixel=false", "--client-option", "enableTrzsz=false", "--terminal-type", "xterm-256color", "chroot", "/host", "bash"]
    volumes:
      - type: bind
        source: /
        target: /host
    networks:
      - pcs
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN

networks:
  pcs:
    external: true

x-casaos:
  architectures:
    - amd64
    - arm64
  main: yunderaterminalboth
  author: yundera
  developer: yundera
  icon: https://cdn-icons-png.flaticon.com/512/2933/2933245.png
  tagline:
    en_us: "Secure dual-auth terminal - hash OR password"
  category: Utilities
  description:
    en_us: "A secure terminal supporting BOTH hash-based and username/password authentication. Access via URL hash for quick access, or login page for session-based access. Maximum flexibility!"
  title:
    en_us: "Yundera Terminal (Dual Auth)"
  store_app_id: yunderaterminalboth
  is_uncontrolled: false
  # Can use hash directly or go to login page
  index: /?hash=$AUTH_HASH
  webui_port: 80
